### ISSUE TITLE
TailwindSort fails on htmldjango file.

### ISSUE THREAD

**Issue by akthe-at** [luckasRanarison/tailwind-tools.nvim#1]
**Describe the bug**
TailwindSortSelection works just fine when highlighting the class areas within " ". However, TailwindSort fails with the following error message that I shared on Reddit.

```lua
Error executing Lua callback: ...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:180: attempt to call a nil value

stack traceback:

...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:180: in function <...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:169>

Error executing vim.schedule lua callback: ...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:164: Invalid 'end_col': out of range

stack traceback:

[C]: in function 'nvim_buf_set_text'

...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:164: in function 'handler'

...ightly/current/share/nvim/runtime/lua/vim/lsp/client.lua:680: in function 'fn'

vim/_editor.lua:350: in function <vim/_editor.lua:349>

Error executing Lua callback: ...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:180: attempt to call a nil value

stack traceback:

...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:180: in function <...data/lazy/tailwind-tools.nvim/lua/tailwind-tools/lsp.lua:169>
```

**To Reproduce**
Open File
Run :TailwindSort
Read error

**Expected behavior**
For the entire buffer to have its classes be sorted.

**Environment (please complete the following information):**
 - Windows 10
 - Neovim Nightly
 - Nvim-treesitter commit = 3686029
 - tailwind-language-server version= 0.0.16

**Additional context**
htmldjango TS grammar is installed. Still failed even after a reinstall. 

Link to [specific html document](https://github.com/akthe-at/misar_web/blob/development/src/misar_web/home/templates/home/home.html).

**Comment by luckasRanarison** [comment]
It should work now, thanks for the report!

**Comment by akthe-at** [comment]
Can confirm, works great now :) Thank You
