### ISSUE TITLE
[error] no parser avaible for typescript react

### ISSUE THREAD

**Issue by Miguerfi** [luckasRanarison/tailwind-tools.nvim#20]
**Describe the bug**
when i run the cmd "TailwindConcealEnable" returns me the error: [tailwind-tools] No parser avaible for typescriptreact

**To Reproduce**
1. open a buffer with tailwind classes;
2. run :TailwindConcealEnable
3. See error

**Expected behavior**
Attach tailwind tools to all buffers

**Screenshots**
![image](https://github.com/luckasRanarison/tailwind-tools.nvim/assets/91486755/da9260c3-f53a-466a-b0b8-6f7cc47f0009)

**Environment (please complete the following information):**
 - Arch linux
 - Neovim 0.10.0 - dev
 - Nvim-treesitter commit:latest
 - tailwind-language-server version:latest

**Additional context**:
lazy plugin:
```lua
  {
    "luckasRanarison/tailwind-tools.nvim",
    cmd = "TailwindConcealEnable",
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    opts = {}, -- your configuration
  },
```
lspconfig:
```lua
local on_attach = require("nvchad.configs.lspconfig").on_attach
local on_init = require("nvchad.configs.lspconfig").on_init
local capabilities = require("nvchad.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = { "html", "cssls", "tailwindcss", "tsserver" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    on_init = on_init,
    capabilities = capabilities,
  }
end
```

**Comment by luckasRanarison** [comment]
Do you have `tsx` parser installed?

**Comment by Miguerfi** [comment]
aparently not, how i could install?

**Comment by luckasRanarison** [comment]
> - `html`, `css`, `tsx` and your other languages treesitter grammars (using [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter))

It's literally mentioned in the [prerequisites](https://github.com/luckasranarison/tailwind-tools.nvim?tab=readme-ov-file#prerequisites).

```TSInstall tsx```
