### ISSUE TITLE
Allow more flexible queries

### ISSUE THREAD

**Issue by NickCondron** [luckasRanarison/tailwind-tools.nvim#24]
**Is your feature request related to a problem? Please describe.**
I'd like to create a more complex query, but the requirement "The class value should be the second matched item in the query" means I can't really write the query how I want. In order to use a predicate, I have to capture a node. Therefore, I can only use one predicate before I capture the class node.

**Describe the solution you'd like**
Fetch the match using the a specified capture-id (which would have to be standardized). Say for example `@_twtools_class`.

**Describe alternatives you've considered**
You could also use treesitter-directives. This approach would be more complicated, but it would allow multiple class nodes per query. The built-in `set!` directive (:h treesitter-directive-set!) would be sufficient for this purpose, but there could be a unique directive for this plugin.

**Additional context**
This would be a breaking change. You could try to fallback to the original behavior if the specified capture-id is not found.

Example query based on `html/class.scm`, but restricting which elements it applies to:

```scm
(start_tag
  (tag_name) @_tag_name
  (#eq? @_tag_name "div")
  (attribute
    (attribute_name) @_attribute_name
    (#eq? @_attribute_name "class")
    (quoted_attribute_value
      (attribute_value) @_twtools_class))) ; Third capture, but name is as-specified
```

**Comment by luckasRanarison** [comment]
You're absolutely right, that rule was too restrictive. So I've introduced `@tailwind` to match the actual class value, like so:

```scheme
(start_tag
  (tag_name) @_tag_name
  (#eq? @_tag_name "div")
  (attribute
    (attribute_name) @_attribute_name
    (#eq? @_attribute_name "class")
    (quoted_attribute_value
      (attribute_value) @tailwind)))
```
