### ISSUE TITLE
Bug on svelte files tw concealing inside script clause

### ISSUE THREAD

**Issue by directormac** [luckasRanarison/tailwind-tools.nvim#32]
**Describe the bug**
Concealign random texts in the script section on svelte

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ccb3f9e3-0e1e-4252-998d-9e8d7221bbdb)

**Environment (please complete the following information):**
Using LazyVim and adding your tool with this configuration

```lua
  {
    "luckasRanarison/tailwind-tools.nvim",
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    opts = {
      document_color = {
        enabled = true, -- can be toggled by commands
        kind = "inline", -- "inline" | "foreground" | "background"
        inline_symbol = "󰝤 ", -- only used in inline mode
        debounce = 200, -- in milliseconds, only applied in insert mode
      },
      conceal = {
        enabled = true, -- can be toggled by commands
        min_length = 60, -- only conceal classes exceeding the provided length
        symbol = "󱏿", -- only a single character is allowed
        highlight = { -- extmark highlight options, see :h 'highlight'
          fg = "#38BDF8",
        },
      },
    }, -- your configuration
  },
```

**Additional context**

working fine at [this commit](https://github.com/luckasRanarison/tailwind-tools.nvim/commit/da8eee8a6ae62e99ffc30e0c9ab862cbdc76b3ed)

**Comment by luckasRanarison** [comment]
It should be fixed now, thanks for the report!
