### ISSUE TITLE
Language server not activated for `eelixir` filetype

### ISSUE THREAD

**Issue by linduxed** [luckasRanarison/tailwind-tools.nvim#54]
### Describe the bug

When I load a `.html.heex` file, i.e. the Elixir template files that are used in Phoenix projects, the language server does not get activated.

The filetype that gets set for these files is `eelixir`, which should be something that is already supported through the passing of this `server` table...:

https://github.com/luckasRanarison/tailwind-tools.nvim/blob/0f2f03d535578d16042cd601e85c9236bd469456/lua/tailwind-tools/filetypes.lua#L27-L33

...through `get_server_map`...:

https://github.com/luckasRanarison/tailwind-tools.nvim/blob/0f2f03d535578d16042cd601e85c9236bd469456/lua/tailwind-tools/filetypes.lua#L47

...as the value for the `includeLanguages` key in the `settings` table that the language server gets initialized with:

https://github.com/luckasRanarison/tailwind-tools.nvim/blob/0f2f03d535578d16042cd601e85c9236bd469456/lua/tailwind-tools/lsp.lua#L137

### To reproduce

1. Open up a `.html.heex` file
2. Write `class="lime"` (replace `lime` with something else that Tailwind has suggestions for)

### Expected behavior

I should be able getting completions.

### Environment

 - Operating system: Linux, Arch
 - Neovim version or commit: `v0.10.1`
 - Nvim-treesitter commit: `929ca9c76ee20bb27cffbde4ee9053b6c54d616`
 - tailwind-language-server version: `0.0.24`

### Problem circumvention

Something I tried that "solves" the problem (although I'm not sure whether you think that it's an adequate solution) is extending the `filetypes` list with `eelixir`, right underneath this line:

https://github.com/luckasRanarison/tailwind-tools.nvim/blob/0f2f03d535578d16042cd601e85c9236bd469456/lua/tailwind-tools/filetypes.lua#L17

This makes the server initiate as expected.

I noticed that `nvim-lspconfig` adds `eelixir` to their `filetypes` list as can be seen here:

https://github.com/neovim/nvim-lspconfig/blob/dd329912c8d446240584a2dbcd3802af3a19105a/lua/lspconfig/server_configurations/tailwindcss.lua#L17

I don't understand why the `includeLanguages` map does not do the trick, as it's my understanding that it should be sufficient.

**Comment by luckasRanarison** [comment]
My bad, I forgot to add `eelixir` to supported filetypes through treesitter. But I'm also using v0.10 and `*.html.heex` files are set to `heex`, I'm not an elixir user but what's the difference?

**Comment by luckasRanarison** [comment]
Actually, only languages from the treesitter and luapattern map affects the language server startup.

**Comment by luckasRanarison** [comment]
Fixed

**Comment by linduxed** [comment]
Thanks for the very quick resolution!
