### ISSUE TITLE
cmp dependency instructions incorrect

### ISSUE THREAD

**Issue by cameronr** [luckasRanarison/tailwind-tools.nvim#64]
**Describe the bug**
Following the Lazy installation instructions along with the cmp instructions results in a "Plugin tailwind-tools.nvim not found" error.

I think the dependency instructions are incorrect. The main installation instructions rename the plugin to `tailwind-tools` but the dependency does not. I believe the correct way to specify the dependency is either just `tailwind-tools` or:

```lua
      {
        'luckasRanarison/tailwind-tools.nvim',
        name = 'tailwind-tools',
      },
```

[Here's the source issue on reddit](https://www.reddit.com/r/neovim/comments/1glkt7k/lazynvim_dependency_doesnt_load_with_the_plugin/)

**To Reproduce**
1. Install with this plugin spec:

```lua
return {
  {
    'luckasRanarison/tailwind-tools.nvim',
    name = 'tailwind-tools',
    build = ':UpdateRemotePlugins',
    dependencies = {
      'nvim-treesitter/nvim-treesitter',
      'nvim-telescope/telescope.nvim',
      'neovim/nvim-lspconfig',
    },
    opts = {},
  },
}
```
2. Specify the cmp dependency as `luckasRanarison/tailwind-tools.nvim`
3. Trigger cmp loading (if lazy loaded)

**Expected behavior**
No error is generated

**Screenshots**
A "Plugin tailwind-tools.nvim not found" is displayed

![Screenshot 2024-11-09 at 20 54 40](https://github.com/user-attachments/assets/0c07ef5f-fff0-4d75-8e28-81c4e86f6c4e)

**Environment (please complete the following information):**
Darwin astrotop.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64 x86_64

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by luckasRanarison** [comment]
Thanks for pointing that out :)
